init:
    # BGM

    define music_waltz = f"{sh_path}/bgm/Waltz_in_A_Minor.ogg"
    define music_bloom = f"{sh_path}/bgm/Bloom.ogg"

    # SOUND EFFECTS

    define sfx_nature = sh_sfx("nature")
    define sfx_waves = sh_sfx("waves")
    define sfx_rockskip = sh_sfx("rockskip")
    define sfx_rockskip_fail = sh_sfx("rockskip_fail")
    define sfx_rocksplash = sh_sfx("rocksplash")
    define sfx_phonedial = sh_sfx("phonedial")
    define sfx_phonepickup = sh_sfx("phonepickup")
    define sfx_car_driveup = sh_sfx("car_driveup")
    define sfx_clap = sh_sfx("clap")
    define sfx_crickets = sh_sfx("crickets")
    define sfx_gostone_soft = sh_sfx("gostone_soft")
    define sfx_gostone = sh_sfx("gostone_medium")
    define sfx_gostone_hard = sh_sfx("gostone_hard")
    define sfx_gostone_soft_stress1 = sh_sfx("gostone_soft_stress1")
    define sfx_gostone_soft_stress2 = sh_sfx("gostone_soft_stress2")
    define sfx_gostone_stress1 = sh_sfx("gostone_medium_stress1")
    define sfx_gostone_stress2 = sh_sfx("gostone_medium_stress2")
    define sfx_bedsheets = sh_sfx("bedsheets")
    define sfx_metalclink = sh_sfx("metalclink")
    define sfx_arcadeambience = sh_sfx("arcade_ambient")
    define sfx_airhockey_rally = sh_sfx("airhockey_rally")
    define sfx_airhockey_score1 = sh_sfx("airhockey_score1")
    define sfx_airhockey_score2 = sh_sfx("airhockey_score2")
    define sfx_hadouken = sh_sfx("hadouken")
    define sfx_yogafire = sh_sfx("yogafire")
    define sfx_gameover = sh_sfx("gameover")
    define sfx_shower = sh_sfx("shower")
    define sfx_taps1 = sh_sfx("taps1")
    define sfx_taps2 = sh_sfx("taps2")
    define sfx_taps3 = sh_sfx("taps3")
    define sfx_taps4 = sh_sfx("taps4")
    define sfx_lightswitch_on = sh_sfx("lightswitch_on")
    define sfx_lightswitch_off = sh_sfx("lightswitch_off")
    define sfx_carsambient = sh_sfx("carsambient")
    define sfx_cellphonering = sh_sfx("cellphonering")
    define sfx_bicyclecrash = sh_sfx("bicyclecrash")
    define sfx_hospital = sh_sfx("hospital")
    define sfx_teacup_loudclink = sh_sfx("teacup_loudclink")
    define sfx_chairscrape = sh_sfx("chairscrape")
    define sfx_phonenotif = sh_sfx("phonenotif")
    define sfx_bushes = sh_sfx("bushes")
    define sfx_alarmbeep = sh_sfx("alarmbeep")
    define sfx_collapse = sh_sfx("collapse")
